module.exports = {
  study: [
    {
      type: 'autogenerated',
      dirName: 'study',
    },
  ],
  projects: [
    {
      type: 'autogenerated',
      dirName: 'projects',
    },
  ],
  maths: [
    {
      type: 'autogenerated',
      dirName: 'maths',
    },
  ],
  tutorials: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],
  awesome_tools: [
    {
      type: 'autogenerated',
      dirName: 'awesome-tools',
    },
  ],

};
