module.exports = {
  study: [
    {
      type: "autogenerated",
      dirName: "study",
    },
  ],
  projects: [
    {
      type: "autogenerated",
      dirName: "projects",
    },
  ],
  linux: [
    {
      type: "autogenerated",
      dirName: "linux",
    },
  ],
  tutorials: [
    {
      type: "autogenerated",
      dirName: "tutorials",
    },
  ],
  windows: [
    {
      type: "autogenerated",
      dirName: "windows",
    },
  ],
};
