module.exports = {
  study: [
    {
      type: 'autogenerated',
      dirName: 'study',
    },
  ],
  projects: [
    {
      type: 'autogenerated',
      dirName: 'projects',
    },
  ],
  maths: [
    {
      type: 'autogenerated',
      dirName: 'maths',
    },
  ],
  personal_setup: [
    {
      type: 'autogenerated',
      dirName: 'personal-setup',
    },
  ],
};
